version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    environment:
      DJANGO_MANAGEPY_MIGRATE: 'on'
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db