version: '3'

services:
  db:
    restart: always
    image: postgres:latest
    networks:
      - database_network
  web:
    image: amadeus:latest
    build:
      context: .
      args:
        requirements: requirement_files/development_requirement.txt 
    environment:
      DJANGO_MANAGEPY_MIGRATE: 'on'
    volumes:
      - .:/code
    depends_on:
      - db
    stdin_open: true
    tty: true
    networks:
      - nginx_network
      - database_network
  nginx:
    image: nginx:1.13
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - web
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge
  database_network:
    driver: bridge