version: '3'

services:
  db:
    restart: always
    image: postgres:latest
    networks:
      - database_network
    ports:
      - 5432:5432
  web:
    image: amadeus:latest
    build:
      context: .
      args:
        requirements: requirement_files/development_requirement.txt 
    environment:
      DJANGO_MANAGEPY_MIGRATE: 'on'
      SECRET_KEY: 'foo'
      FCM_SERVER_KEY: 'boo'
      DEBUG: 1
      PORT: 8000
    volumes:
      - .:/code
    depends_on:
      - db
    stdin_open: true
    tty: true
    networks:
      - nginx_network
      - database_network
  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
  nginx:
    image: nginx:1.13
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - web
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge
  database_network:
    driver: bridge

volumes:
  redisdata:
