version: '3'

services:
  db:
    restart: always
    image: postgres:latest
    ports:
      - "8010:5432"
  web:
    image: amadeus:latest
    build:
      context: .
      args:
        requirements: requirement_files/development_requirement.txt 
    environment:
      DJANGO_MANAGEPY_MIGRATE: 'on'
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    stdin_open: true
    tty: true